Repository openshift/openshift-tests, pull requests merged in 2020-03, with the labels that each got.

#15 OCP-27589 Don't use ipv4 addresses in CatalogSources generated by marketplace
  test/extended/operators/olm.go
Labels: lgtm, size/M

#11 catch packages Init error
  test/extended/util/framework.go
Labels: size/XS

#14 OCP-24818 Checking OLM descriptors
  test/extended/operators/olm.go
Labels: size/S

#6 [AUTO][OLM][OCP-21130] - [bug ALM-736]Fetching non-existent `PackageManifest` should return 404
  test/extended/operators/olm.go
Labels: size/S
