Repository openshift/openshift-tests, pull requests merged in 2020-04, with the labels that each got.

#22 OLM-Medium-OCP-21611 package manifest object has the description from CSV
  test/extended/operators/olm.go
  test/extended/testdata/olm/etcd-custom-csc.yaml
Labels: lgtm

#30 Bug 1820731: samename test flake fix
  test/extended/marketplace/marketplace_diffname.go
Labels: bugzilla/valid-bug

#35 [marketplace] Remove CSC related tests
  test/extended/marketplace/marketplace_diffname.go
  test/extended/marketplace/marketplace_lables.go
Labels: approved, bugzilla/valid-bug, lgtm
